/**
 * Post-build step.
 *
 *   1. Generates build/client/_redirects from data/redirects.csv — the map of
 *      legacy WordPress URLs, so existing Google rankings survive the move.
 *   2. Publishes the prerendered /404 page as 404.html, which is the file
 *      static hosts look for.
 *
 * Both outputs are host-agnostic conventions. Moving to another host means
 * translating _redirects into that host's format; nothing else changes.
 */
import { readFileSync, writeFileSync, existsSync, copyFileSync } from 'node:fs'
import { parse } from 'csv-parse/sync'

const OUT = 'build/client'

/* ---- page-level redirects (hand-mapped, from the audit spec §3.2) ---- */
const PAGES = [
  ['/trim-doors-catalogue', '/products'],
  ['/mouldings', '/products/trim-mouldings'],
  ['/interior-doors', '/products/interior-doors'],
  ['/doors', '/products/interior-doors'],
  ['/door-hardware', '/products/door-hardware'],
  ['/staircase-parts-accessories', '/products/stair-railing'],
  ['/products-new', '/products'],
  ['/upcp_product', '/products'],
]

const rows = parse(readFileSync('data/redirects.csv', 'utf8'), {
  columns: true, skip_empty_lines: true, trim: true, bom: true,
})

const seen = new Set()
const lines = ['# Generated by scripts/post-build.mjs — do not edit by hand.', '']

for (const [from, to] of PAGES) {
  if (seen.has(from)) continue
  seen.add(from)
  lines.push(`${from}  ${to}  301!`)
}

lines.push('', `# ${rows.length} product redirects across four legacy URL patterns`)
let skipped = 0
for (const r of rows) {
  const from = r.from_path.replace(/\/$/, '')
  const to = r.to_path.replace(/\/$/, '')
  if (!from || from === to || seen.has(from)) { skipped++; continue }
  seen.add(from)
  lines.push(`${from}  ${to}  ${r.status_code || 301}!`)
}

// Anything still unmatched gets a real 404 rather than a silent bounce to the
// homepage — that is how missing redirects stay visible after launch.
lines.push('', '/*  /404.html  404')

writeFileSync(`${OUT}/_redirects`, lines.join('\n') + '\n')

if (existsSync(`${OUT}/404/index.html`)) {
  copyFileSync(`${OUT}/404/index.html`, `${OUT}/404.html`)
}

console.log(`_redirects written: ${seen.size} rules (${skipped} skipped as duplicate or self-referencing)`)
console.log(existsSync(`${OUT}/404.html`) ? '404.html published' : 'WARNING: no 404 page found')
